[colors.primary]
background = '#101418'
foreground = '#e0e2e8'

[colors.selection]
text = '#e0e2e8'
background = '#084b72'

[colors.cursor]
text = '#101418'
cursor = '#99ccfa'

[colors.normal]
black   = '#101418'
red     = '#e64c48'
green   = '#72d66e'
yellow  = '#dbd07b'
blue    = '#4d87bc'
magenta = '#819fbb'
cyan    = '#99ccfa'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f61'
green   = '#89e086'
yellow  = '#e8de97'
blue    = '#a3daff'
magenta = '#41809b'
cyan    = '#607aa6'
white   = '#ffffff'
